macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  script: |
    pushd "$(brew --repo)"
    git fetch
    git reset --hard origin/master
    brew update
    popd

    brew install automake autoconf libtool pkg-config texinfo coreutils gnu-getopt python@3 \
      cmake ninja ccache bison byacc gettext wget pcre llvm@15 openjdk@11 maven node

    git clone https://github.com/apache/doris

    cd doris/thirdparty
    bash build-thirdparty.sh -j "$(nproc)"

    kernel="$(uname -s | awk '{print tolower($0)}')"
    arch="$(uname -m)"
    tar -cf - installed | xz -z -T0 - >"doris-thirdparty-prebuilt-${kernel}-${arch}.tar.xz"

  artifacts:
    path: doris/thirdparty/doris-thirdparty-prebuilt-*.tar.xz
