name: Build (macOS arm64)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch
        required: true
        type: choice
        options:
          - master
          - branch-1.2-lts
          - branch-2.0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: CIRRUS-CI
    env:
      GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          submodules: true

      - name: Build (${{ inputs.branch }})
        id: build
        run: |
          branch=${{ inputs.branch }}
          if [[ "${branch}" == 'master' ]]; then
            tag='automation'
          else
            tag="automation-${branch/branch-/}"
          fi

          git clone -b "${branch}" https://github.com/apache/doris /tmp/doris
          pushd /tmp/doris
          current_version="$(git log -1 --format='%H')"
          echo "current_version: ${current_version}"
          popd

          cd .github/cirrus-ci-tools/src
          config="../../cirrus-ci/${branch}.yml"

          url=$(./trigger-cirrus-ci.py --token ${{ secrets.CIRRUS_CI_TOKEN }} \
            --repository adonis0147/doris-thirdparty --branch main --config "${config}")

          echo "The artifact url: ${url}"
          curl -L ${url} -o binary.zip
          unzip binary.zip

          gh release upload --repo ${{ github.repository }} --clobber "${tag}" doris/thirdparty/*.tar.xz
          gh release upload --repo apache/doris-thirdparty --clobber "${tag}" doris/thirdparty/*.tar.xz

          echo "current_version=${current_version}" >>$GITHUB_OUTPUT

      - name: Release
        run: |
          branch=${{ inputs.branch }}
          current_version="${{ steps.build.outputs.current_version }}"
          content="$(gh release view cirrus-ci | sed -n '/--/,$p' | awk '{ if (NR > 1) print $0 }')"

          content="$(echo "${content}" | sed "{
            s/Update Time:.*/Update Time: *$(date)*/
            s/${branch}:.*/${branch}: *${current_version}*/
          }")"

          echo "${content}" >release_note.md
          gh release edit -F release_note.md cirrus-ci
